ports:
    - port: 3000
      onOpen: open-browser
tasks:
    - init: >
        npm i vercel -g &&
        npm install &&
        cp .env.example .env
      command: >
        npm i vercel -g
vscode:
  extensions:
    - sirtori.indenticator@0.7.0:XXP11mgN1178eZKRS1jiWQ==